#166151251 fix flake 8 errors
andela/wg-baqi pull request #2
Opened 2019-05-31 07:01 UTC by kburudi

#### What does this PR do?
Fixes flake 8 syntactical errors

#### Description of Task to be completed?
Remove errors arising as a result of adding flake 8 linters ie, indentation errors, line length, and unused imports.

#### How should this be manually tested?
```
  $ pip install flake 8
```
- set default editor linter to flake8

#### What are the relevant pivotal tracker stories?
#166151251

2019-05-31 08:16 UTC, wekesa931 commented on tasks.py
> +        create_settings(
Consider changing this to `create-settings` as it is deprecated

2019-05-31 08:56 UTC, wangonya commented
Kindly edit the PR description on installing flake8 to be `pip install flake8` instead of `pip install flake 8`

2019-05-31 08:58 UTC, wangonya requested changes
Kindly edit the PR description on installing flake8 to be `pip install flake8` instead of `pip install flake 8`

2019-05-31 09:31 UTC, jmusila requested changes
I think you can add the command to run `flake8` from the terminal after installation.

2019-06-03 06:24 UTC, wangonya approved these changes

2019-06-03 07:12 UTC, jmusila approved these changes

2019-06-03 08:28 UTC, wekesa931 approved these changes

2019-06-03 08:37 UTC, willeswa approved these changes
LGTM

2019-06-03 10:18 UTC, caveinn commented
@kburudi  kindly check on the dropping coverage

2019-06-04 07:59 UTC, merged