#166151256 Allow Create Users via REST API
andela/wg-baqi pull request #5
Opened 2019-06-06 07:48 UTC by jonathanmusila

#### What does this PR do?
- Allow creation of users via REST API

#### Description of the Tasks to be completed?
- [x] write unit tests
- [x] add `POST` endpoint for registering new users
- [x] allow `GET` to see all new users created by a certain user or using the API key
- [x] create a command to allow a user to create users
- [x] create command to allow users to get a list of all users they created 

#### How should this be manually tested?
- Clone the repository to your local branch

```$ git clone https://github.com/andela/wg-baqi.git```
- $ cd to the wg-baqi directory, create a virtual environment and install the dependencies

```$ cd wg-baqi
$ virtualenv venv
$ source venv/bin/activate
$ pip install -r requirements.txt
Activate bootstrap and run the server```

```$ invoke bootstrap-wger --settings-path ./wger/settings.py --no-start-server
$ python manage.py runserver```

- Navigate to the endpoint http://127.0.0.1:8000/api/v2/signup/
- To get API Key:
   1. while the server is running, open the browser
   2. browse the endpoint http://127.0.0.1:8000/en/user/api-key
   3. generate an API key and copy it
- Open Postman and add the key as shown below:
<img width="1132" alt="Screenshot 2019-06-06 at 10 42 47" src="https://user-images.githubusercontent.com/42172425/59015523-dd65c280-8847-11e9-835b-1b19657022b0.png">
- add new user 

#### What are the relevant pivotal tracker stories?
#166151256

2019-06-06 11:54 UTC, wangonya requested changes

2019-06-06 11:54 UTC, wangonya commented on wger/core/api/views.py
> +        creat = UserProfile.objects.get(user=self.request.user)
Kindly spell `create` correctly 😅

2019-06-07 14:27 UTC, wangonya approved these changes

2019-06-08 11:30 UTC, willeswa approved these changes
LGTM

2019-06-08 17:39 UTC, ceexon approved these changes

2019-06-10 11:43 UTC, merged